config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "products#showcase"
  resources :products, only: %i[
    new
    create
    edit
    index
    update
    show
  ]

  get "/listings", to: "products#listings", as: "listings"

  resources :payments do
    get "success"
  end

  resources :orders, only: %i[
    index
    show
    update
  ]

  resources :orders do
    get "checkout"
    put "packed"
    put "dispatched"
  end

  resources :order_line_items do
    put "increment"
    put "decrement"
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_one :payment
  has_many :order_line_items
  has_many :products, through: :order_line_items

  enum(state: { created: 0, paid: 1, packed: 2, dispatched: 3 })

  scope :ordered, -> { where(state: %w[paid packed dispatched]) }

  def total_quantity
    order_line_items.map(&:quantity).sum
  end

  def subtotal
    order_line_items.map(&:subtotal).sum
  end

  def update_total(postage_fee)
    update(total: subtotal + postage_fee)
  end

  def editable?
    state == "created"
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :find_order, only: %i[show update checkout packed dispatched]
  before_action :find_line_item, only: :update

  def index
    return not_found unless current_user&.is_admin?

    if state.present?
      @title = "#{state} orders".titleize
      @orders = Order
                .where(state: state)
                .ordered
                .page(page_params)
                .per(40)
      @state = state
    else
      @title = "Orders"
      @orders = Order
                .ordered
                .page(page_params)
                .per(40)
    end
  end

  def show
    @title = if @order.state == "created"
               "Cart"
             else
               "Order ##{@order.id}"
             end
    @line_items = @order.order_line_items
    @postage_fee = 0.75
  end

  def new; end

  def update
    if @line_item
      @line_item.increase_quantity(quantity)
    else
      @order.order_line_items.create(product_id: product_id, quantity: quantity)
    end
    redirect_back(fallback_location: order_path(cart.id))
  end

  def checkout
    # @order.paid!
    # @order.update_total(0.75)
    # @order.order_line_items.each do |product|
    #   Product.find(product.product_id).decrease_quantity(product.quantity)
    # end
    # clear_cart
    # redirect_to payment_success_path(@order.id)
    @line_items = @order.order_line_items
    @postage_fee = 0.75
    @total = @order.subtotal + @postage_fee
    @intent = Stripe::PaymentIntent.create({
                                             amount: (@total * 100).to_i,
                                             currency: "gbp",
                                             automatic_payment_methods: {
                                               enabled: true
                                             }
                                           })
  end

  def packed
    return not_found unless current_user&.is_admin?

    @order.packed!
    redirect_back(fallback_location: order_path(@order.id))
  end

  def dispatched
    return not_found unless current_user&.is_admin?

    @order.dispatched!
    redirect_back(fallback_location: order_path(@order.id))
  end

  private

  def page_params
    params.permit(:page)[:page]
  end

  def state
    params.permit(:state)[:state]
  end

  def id
    params.permit(:id)[:id]
  end

  def order_id
    params.permit(:order_id)[:order_id]
  end

  def product_id
    params.permit(:product_id)[:product_id]
  end

  def quantity
    params.permit(:quantity)[:quantity]
  end

  def find_order
    @order = Order.find(order_id || id)
  end

  def find_line_item
    @line_item = @order.order_line_items.find_by(product_id: product_id)
  end
end

app/views/orders/_checkout_form.html.slim
h4.text-center.pb-3 Please enter your details

form action="/submissions" method="post" id="payment-form"
  input type="hidden" name="client_secret" value="#{@intent.client_secret}"
  input type="hidden" name="authenticity_token" value="#{form_authenticity_token}"

  .field.pb-2
    #address-element
  
  .field.pb-2
    #payment-element

  input type="submit" value="Pay #{number_to_currency(@total, locale: 'en-GB')}" class = "btn btn-secondary w-100 mt-3"

javascript:
  const stripe = Stripe('pk_test_51N4PSQC5kweBrNcIAP4Ti8MvmDzTfPSzwKC8EkLvA7Y88wSTcoBCleqg9kVIbIey9BcgIgt43UgrQY1kbALnuXoy00tI6eeaTX');

  const clientSecret = document.getElementsByName("client_secret")[0].value;
  const appearance = { /* appearance */ };
  const addressOptions = { mode: 'shipping' };
  const elements = stripe.elements({ clientSecret, appearance });
  const addressElement = elements.create('address', addressOptions);
  addressElement.mount('#address-element');
  const paymentElement = elements.create('payment');
  paymentElement.mount('#payment-element');
  const form = document.querySelector("#payment-form")
  form.addEventListener("submit", async (event) => {
    event.preventDefault()
    elements.submit()
    await stripe.confirmPayment ({
      elements: elements,
      confirmParams: {
        shipping: addressElement,
        return_url: `${window.location}`
      },
    });
  });

app/views/orders/_order_items.html.slim
- if @line_items.any?
  - @line_items.each do |line_item|
    .card.my-2.shadow-sm
      .row
        .col-4
          - if line_item.product.images.any?
            = image_tag line_item.product.images[0], class: 'img-fluid'
          -else
            = image_tag "product", class: 'img-fluid'
        .col-8
          .card-body
            h5.card-title.mb-3
              = line_item.product.name
            .row
              .col-3
                h6.card-subtitle.mb-2.text-muted Unit Price: 
                h6.card-subtitle.mb-2.text-muted Quantity: 
                h6.card-subtitle.mb-2.text-muted Subtotal: 
              .col-3
                h6.card-subtitle.mb-2.text-muted
                  = number_to_currency(line_item.product.price, locale: :"en-GB")
                h6.card-subtitle.mb-2.text-muted
                  = line_item.quantity
                h6.card-subtitle.mb-2.text-muted
                  = number_to_currency(line_item.subtotal, locale: :"en-GB")
            - if @order.editable?
              .row.pt-4
                .col-7
                  = button_to "Remove from Cart", order_line_item_path(line_item), method: :delete, class: "btn btn-danger"
                .col
                  .input-group
                    = button_to "-", order_line_item_decrement_path(line_item), method: :put, params: { decrement: 1 }, class: "btn btn-outline-secondary"
                    = content_tag(:input, nil, type: "text", placeholder: "#{line_item.quantity}", disabled: true, class: "form-control")
                    = button_to "+", order_line_item_increment_path(line_item), method: :put, params: { increment: 1 }, class: "btn btn-outline-secondary"
            - else
              h6.card-subtitle.mb-2.text-muted
                = "SKU: #{line_item.product.sku}"
- else
  h5.text-center
    | Your cart is empty

app/views/orders/_summary.html.slim
h4.card-title.mb-5.text-center
  | Order Summary
.row
  .col-1
  .col-10
    .row.mb-5
      .col-6
        p Subtotal: 
        p Included VAT:
        p Postage:
        p.fw-bold Total:
      .col-6
        p.text-end
          = number_to_currency(@order.subtotal, locale: "en-GB")
        p.text-end
          = number_to_currency((@order.subtotal)*0.2, locale: "en-GB")
        p.text-end
          = number_to_currency(@postage_fee, locale: "en-GB")
        p.text-end.fw-bold
          = number_to_currency(@order.subtotal + @postage_fee, locale: "en-GB")
    - if @order.editable? && @order.order_line_items.any?
      = link_to "Proceed to Checkout", order_checkout_path(@order), class: ["btn", "btn-outline-secondary", "w-100"]
    - elsif @order.order_line_items.any?
      .row.mb-5
        h5.card-subtitle.text-center.mb-3
          | Customer Details
        p.text-center
          span.fw-bold
            | Meg Goffin
          br
          | Adastral Park
          br
          | Barrack Square, Martlesham Heath
          br
          | Martlesham, Ipswich
          br
          | IP5 3RE
      .row.mb-5
        .col-6
          p Current status:
        .col-6
          p.text-capitalize.fw-bold.text-end
            = @order.state
        - if @order.paid?
          = button_to "Mark as Packed", order_packed_path(@order.id), method: :put, class: ["btn", "btn-outline-secondary", "w-100"]
        - if @order.packed?
          = button_to "Mark as Dispatched", order_dispatched_path(@order.id), method: :put, class: ["btn", "btn-outline-secondary", "w-100"]
  .col-1

  
  

app/views/orders/checkout.html.slim
.row
  .col-md-8
    = render 'checkout_form'
  .col-md-4
    .card.my-2.shadow-sm
      .card-body
        = render 'summary'

app/views/orders/index.html.slim
h2.text-center.pb-5
  | Orders
.d-flex.justify-content-center.pb-3
  = button_to "All", orders_path, method: :get, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
  = button_to "Ordered", orders_path, method: :get, params: { state: "ordered"}, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
  = button_to "Packed", orders_path, method: :get, params: { state: "packed"}, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
  = button_to "Dispatched", orders_path, method: :get, params: { state: "dispatched"}, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
.d-flex.justify-content-center.pb-3
  = paginate @orders
.row
  - if @orders.any?
    .table-responsive
      table.table.table-hover.table-light.table-sm.table-fixed
        tbody
          thead
            tr
              th Order Number
              th # of Items
              th Total
              th Ordered At
              th Status
          - @orders.each do |order|
              tr.data-row
                td = link_to "Order ##{order.id}", order_path(order.id)
                td = "#{order.total_quantity} items"
                td = number_to_currency(order.total, locale: "en-GB")
                td = order.created_at.strftime("%d/%m/%y %H:%M")
                td.text-capitalize = order.state
  - else
    h5
      | You currently have no
      = " #{@state}" if @state.present?
      |  orders
.d-flex.justify-content-center.pb-3
  = paginate @orders

app/views/orders/show.html.slim
.row
  .col-md-8
    = render 'order_items'
  .col-md-4
    .card.my-2.shadow-sm
      .card-body
        = render 'summary'