config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "products#showcase"
  resources :products, only: %i[
    new
    create
    edit
    index
    update
    show
  ]

  get "/listings", to: "products#listings", as: "listings"

  resources :payments do
    get "success"
  end

  resources :orders, only: %i[
    index
    show
    update
  ]

  resources :orders do
    get "checkout"
    put "packed"
    put "dispatched"
  end

  resources :order_line_items do
    put "increment"
    put "decrement"
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :order_line_items
  has_many :orders, through: :order_line_items
  has_many_attached :images, dependent: :destroy

  enum(category: { uncategorised: 0, pebbles: 1, rocks: 2, boulders: 3 })

  scope :in_stock, -> { where("quantity > 0") }

  validates :name, presence: { message: "can't be blank" },
                   uniqueness: true,
                   length: { maximum: 128 }

  validates :sku, presence: { message: "can't be blank" },
                  uniqueness: true,
                  length: { maximum: 128 }

  validates :price, presence: { message: "can't be blank" },
                    numericality: { greater_than: 0 }

  validates :quantity, presence: { message: "can't be blank" },
                       numericality: { greater_than_or_equal_to: 0 }

  def decrease_quantity(decrement)
    update(quantity: quantity - decrement.to_i)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    if category.present?
      @title = "Shop #{category}"
      @products = Product
                  .in_stock
                  .where(category: category)
                  .with_attached_images
                  .page(page_params)
    else
      @title = "Shop All"
      @products = Product
                  .in_stock
                  .with_attached_images
                  .page(page_params)
    end
  end

  def show
    @product = Product.find(id)
    @title = Product.name
  end

  def new
    return not_found unless current_user&.is_admin?

    @title = "New Listing"
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @product.images.attach(product_params[:images])

    if @product.valid?
      respond_to do |format|
        format.html { redirect_to product_path(@product), notice: "Product was successfully created." }
      end
    else
      render :new
    end
  end

  def showcase
    @title = "Home"
  end

  def listings
    return not_found unless current_user&.is_admin?

    @products = Product
                .all
                .page(page_params)
                .per(40)
    @title = "Listings"
  end

  private

  def product_params
    params.require(:product).permit(:name, :sku, :price, :quantity, :images)
  end

  def page_params
    params.permit(:page)[:page]
  end

  def id
    params.permit(:id)[:id]
  end

  def category
    params.permit(:category)[:category]
  end
end

app/views/products/_form.html.slim
= form_with(model: @product) do |form|
  .field.mb-3
    .input-group
      = form.label :name, class:"input-group-text"
      = form.text_field :name, class: "form-control"
    - @product.errors.full_messages_for(:name).each do |message|
      .text-danger
        = message
  .field.mb-3
    .input-group
      = form.label :sku, class:"input-group-text text-uppercase"
      = form.text_field :sku, class: "form-control"
    - @product.errors.full_messages_for(:sku).each do |message|
      .text-danger
        = message
  .field.mb-3
    .input-group
      = form.label :price, class:"input-group-text"
      = form.number_field :price, class: "form-control", step: 0.01
    - @product.errors.full_messages_for(:price).each do |message|
      .text-danger
        = message
  .field.mb-3
    .input-group
      = form.label :quantity, class:"input-group-text"
      = form.number_field :quantity, class: "form-control"
    - @product.errors.full_messages_for(:quantity).each do |message|
      .text-danger
        = message
  .field.mb-3
    .input-group
      = form.label :images, class:"input-group-text"
      = form.file_field :images, multiple: true, data: {"direct-upload-url":"#{rails_direct_uploads_url}"},  name: "product[images]", class: "form-control"
    - @product.errors.full_messages_for(:images).each do |message|
      .text-danger
        = message
  .actions.d-flex.justify-content-center
    = form.submit class: ["btn", "btn-secondary", "m-3"]
    = link_to 'Back', listings_path, class: ["btn", "btn-secondary", "m-3"]

app/views/products/_product.html.slim
.col-lg-3.col-md-4
  .card.my-2.shadow-sm
    - if product.images.any?
      = image_tag product.images[0], class: 'card-img-top'
    -else
      = image_tag "product", class: 'card-img-top'
    .card-body
      h5.card-title.mb-2
        = product.name
      h6.card-subtitle.mb-3.text-muted
        = number_to_currency(product.price, locale: :"en-GB")
      .row
        .col-xl-6
          = button_to 'Options', product_path(product.id), method: :get, class: ["btn", "btn-sm", "btn-outline-secondary", "border", "w-100"], type: "button"
        .col-xl-6
          = button_to 'Quick Add', order_path(@cart.id), method: :patch, params: { product_id: product.id, quantity: 1 }, class: ["btn", "btn-sm", "btn-outline-secondary", "border", "w-100"], type: "button"

app/views/products/index.html.slim
h2.text-capitalize.text-center.mb-3
  = @title
.d-flex.justify-content-center.pb-3
  = button_to "All", products_path, method: :get, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
  = button_to "Pebbles", products_path, method: :get, params: { category: "pebbles"}, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
  = button_to "Rocks", products_path, method: :get, params: { category: "rocks"}, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
  = button_to "Boulders", products_path, method: :get, params: { category: "boulders"}, class: ["btn", "btn-secondary", "shadow-lg", "m-1"]
.d-flex.justify-content-center.pb-3
  = paginate @products
.row.pb-3
  - @products.each do |product|
    = render 'product', product: product
.d-flex.justify-content-center.pb-3
  = paginate @products

app/views/products/listings.html.slim
h2.text-center.pb-5
  = @title
.d-flex.justify-content-center.pb-3
  = link_to "New Listing", new_product_path, class: ["btn", "btn-secondary", "shadow-lg"]
.d-flex.justify-content-center.pb-3
  = paginate @products
.row
  - if @products.any?
    .table-responsive
      table.table.table-hover.table-light.table-sm.table-fixed
        tbody
          thead
            tr
              th SKU
              th Name
              th Price
              th Quantity
              th
          - @products.each do |product|
              tr.data-row
                td = link_to "#{product.sku}", product_path(product.id)
                td = product.name
                td = number_to_currency(product.price, locale: "en-GB")
                td = product.quantity
                td = link_to "Edit", edit_product_path(product), class: "btn btn-sm btn-secondary w-100"
  - else
    h5
      | You currently have no products listed
.d-flex.justify-content-center.pb-3
  = paginate @products

app/views/products/new.html.slim
h2.text-center.pb-5
  | New Listing
.row
  .col-md-3
  .col-md-6
    = render 'form', kanban: @product
  .col-md-3

app/views/products/show.html.slim
.row
  .col-md-6
    .
      - if @product.images.any?
        = carousel_for(@product.images)
      - else
        = image_tag 'product', class: ['w-100', 'rounded']
  .col-md-6
    h1
      = @product.name
    h5
      = number_to_currency(@product.price, locale: "en-GB")
    h6
      = "#{@product.quantity} in stock"
    p.text-sm
      | Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum tenetur saepe ullam dignissimos reiciendis exercitationem ducimus minus nulla, inventore sequi velit ab voluptatibus earum repudiandae deleniti animi tempore sed. Voluptatibus!
    = button_to "Add to Cart", order_path(@cart.id), method: :patch, params: { product_id: @product.id, quantity: 1 }, class: ["btn", "btn-sm", "btn-outline-secondary","w-100"]

app/views/products/showcase.html.slim
#showcaseCarousel.carousel.slide.carousel-fade data-bs-ride="carousel"
  .carousel-indicators
    .button type="button" data-bs-target="#showcaseCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"
    .button type="button" data-bs-target="#showcaseCarousel" data-bs-slide-to="1" aria-label="Slide 2"
    .button type="button" data-bs-target="#showcaseCarousel" data-bs-slide-to="2" aria-label="Slide 3"
  .carousel-inner
    .carousel-item.active
      = image_tag "carousel1", class: %w[d-block w-100]
      .carousel-caption.d-none.d-md-block
        .h5 Pebbles
        .p Explore our wide range of smaller stones.
        = button_to "Shop Pebbles", products_path, method: :get, params: { category: "pebbles"}, class: ["btn", "btn-secondary", "mt-2", "shadow-lg"]
    .carousel-item
      = image_tag "carousel2", class: %w[d-block w-100]
      .carousel-caption.d-none.d-md-block
        .h5 Rocks
        .p Explore our selection of mid-size stones.
        = button_to "Shop Rocks", products_path, method: :get, params: { category: "rocks"}, class: ["btn", "btn-secondary", "mt-2", "shadow-lg"]
    .carousel-item
      = image_tag "carousel3", class: %w[d-block w-100]
      .carousel-caption.d-none.d-md-block
        .h5 Boulders
        .p Explore our largest stones.
        = button_to "Shop Boulders", products_path, method: :get, params: { category: "boulders"}, class: ["btn", "btn-secondary", "mt-2", "shadow-lg"]
  button.carousel-control-prev type="button" data-bs-target="#showcaseCarousel" data-bs-slide="prev"
    span.carousel-control-prev-icon aria-hidden="true"
    span.visually-hidden Previous
  button.carousel-control-next type="button" data-bs-target="#showcaseCarousel" data-bs-slide="next"
    span.carousel-control-next-icon aria-hidden="true"
    span.visually-hidden Next